services:
  database:
    image: postgres:17-alpine
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: redis:8.0-alpine
    container_name: cache
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: backend
    command: [ "./wait-for-it.sh", "database:5432", "--",
               "sh", "-c", "python manage.py migrate && python manage.py collectstatic --noinput && uvicorn ecommerce_api.asgi:application --host 0.0.0.0 --port 8000 --reload" ]
    restart: always
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - cache
      - database


volumes:
  database:
  static_volume:
  media_volume: