services:
  db:
    image: postgres:17.4
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  cache:
    image: redis:7.4.2
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    env_file:
      - .env

  web:
    build: .
    command: [ "./wait-for-it.sh", "db:5432", "--",
               "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini" ]
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - cache
      - rabbitmq

  nginx:
    image: nginx:1.27.4
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    ports:
      - "80:80"

volumes:
  db_data: