services:
  database:
    image: postgres:17-alpine
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: redis:8.0-alpine
    container_name: cache
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: backend
    command: [ "./wait-for-it.sh", "database:5432", "--",
               "sh", "-c", "python manage.py migrate && python manage.py collectstatic --noinput && uvicorn ecommerce_api.asgi:application --host 0.0.0.0 --port 8000 --reload" ]
    restart: always
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - cache
      - database

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    restart: "no"
    env_file:
      - .env
    environment:
      - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_DEVICE_NAME=docker-stripe-cli
    volumes:
      - stripe_config:/root/.config/stripe
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "while ! nc -z web 8000; do
        echo 'Waiting for web service on port 8000...';
        sleep 2;
      done;
      echo 'Web service is ready!';
      stripe login --api-key $${STRIPE_SECRET_KEY} &&
      stripe listen --forward-to web:8000/payment/webhook/"
    depends_on:
      - web
    networks:
      - default

volumes:
  database:
  static_volume:
  media_volume:
  stripe_config:
