# Generated by Django 5.2 on 2025-11-29 19:09
import json
from django.db import migrations, models

def convert_value_to_json(apps, schema_editor):
    ProductAttribute = apps.get_model('shop', 'ProductAttribute')
    for pa in ProductAttribute.objects.all():
        try:
            # Attempt to parse as a number first
            value = float(pa.value)
        except (ValueError, TypeError):
            # Fallback to string
            value = pa.value

        pa.value = json.dumps(value)
        pa.save(update_fields=['value'])

class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_category_attributes"),
    ]

    operations = [
        migrations.RunPython(convert_value_to_json, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="productattribute",
            name="value",
            field=models.JSONField(),
        ),
        migrations.AddIndex(
            model_name="productattribute",
            index=models.Index(
                fields=["product"], name="shop_produc_product_979956_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productattribute",
            index=models.Index(
                fields=["attribute"], name="shop_produc_attribu_8385ae_idx"
            ),
        ),
    ]
