name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    services:
      database:
        image: postgres:17.4
        container_name: database
        restart: always
        volumes:
          - database:/var/lib/postgresql/data
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }}" ]
          interval: 10s
          timeout: 5s
          retries: 5
        ports:
          - 5432:5432

      cache:
        image: redis:7.4.2
        container_name: cache
        restart: always
        ports:
          - "6379:6379"

      rabbitmq:
        image: rabbitmq:3-management
        container_name: broker
        restart: always
        ports:
          - "15672:15672"
          - "5672:5672"
        env:
          RABBITMQ_DEFAULT_USER: ${{ secrets.RABBITMQ_USER }}
          RABBITMQ_DEFAULT_PASS: ${{ secrets.RABBITMQ_PASSWORD }}
        healthcheck:
          test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
          interval: 10s
          timeout: 5s
          retries: 3

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      env:
        DOMAIN: localhost:8000
        SITE_NAME: "Luqta eCommerce"
        DB_NAME: ${{ secrets.POSTGRES_DB }}
        DB_USER: ${{ secrets.POSTGRES_USER }}
        DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        DB_HOST: localhost
        REDIS_HOST: localhost
        REDIS_PORT: 6379
        EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
        EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
        DEFAULT_FROM_EMAIL: "Hypex Store <${{ secrets.EMAIL_HOST_USER }}>"
        STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
        GOOGLE_OAUTH2_KEY: ${{ secrets.GOOGLE_OAUTH2_KEY }}
        GOOGLE_OAUTH2_SECRET: ${{ secrets.GOOGLE_OAUTH2_SECRET }}
      run: |
        python manage.py test
